language: c
sudo: required
dist: trusty
cache: ccache

script:
  - sudo ./kexec.sh
after_failure:
  - sudo ./debug-dropbox.sh

env:
  global:
    - TEST_CMD=./test-criu-32cr.sh
    - KPATH=linux
    - CRIU_DIR=criu
    - KCONFIG=config/next
    - LOGS=/log
    - DEBUG=y
    - DEBUG_NO_KEXEC=n
    - CMDLINE="root=/dev/sda1 cgroup_enable=memory swapaccount=1 apparmor=0 console=ttyS0 debug raid=noautodetect vsyscall=none slub_debug=FZP"
  matrix:
    - KNAME=linux-next KGIT="http://kernel.googlesource.com/pub/scm/linux/kernel/git/next/linux-next.git"
    - KNAME=akpm       KGIT="http://kernel.googlesource.com/pub/scm/linux/kernel/git/next/linux-next.git -b akpm"
    - KNAME=tip        KGIT="git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git -b auto-latest"
# master is commented-out as 32-bit C/R is not supported in torvalds
#    - KNAME=master     KGIT="http://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux.git"
